trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo Building the application...
    displayName: 'Build Step'
    - script: |
      python -m pip install --upgrade pip
      pip install -r backend/requirements.txt

  - script: echo Running tests...
    displayName: 'Test Step'
    - script: |
      cd backend
      python3 -m pytest tests/
