name: CI-EduOps

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: List installed packages
      run: |
        pip list

    - name: Check for Python files
      id: check_files
      run: |
        if ! ls *.py 1> /dev/null 2>&1; then echo "No Python files to lint or test"; exit 0; fi

    - name: Lint with flake8
      if: steps.check_files.outputs.has_files == 'true'
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run tests
      if: steps.check_files.outputs.has_files == 'true'
      run: |
        pytest

