name: CI-EduOps

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: List installed packages
      run: |
        pip list

    - name: Lint with flake8
      run: |
        flake8 backend

    - name: Run tests
      run: |
        cd backend
        python3 -m pytest tests/

